[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
restartPolicyType = "on_failure"
startCommand = "npm run start:railway"

[environments.production.variables]
NODE_ENV = "production"
VITE_DEBUG_LOGS = "true" 